### ISSUE TITLE
How to use with 'request' module?

### ISSUE THREAD

**Issue by rightaway** [TooTallNate/node-socks-proxy-agent#6]
When I add the options below to the `request` module, I get an error `TypeError: A "socks" protocol must be specified! Got: undefined`. What's the correct way to use it with `request`?

```
var SocksProxyAgent = require('socks-proxy-agent');

...

        agentClass: SocksProxyAgent,
        agentOptions: {
            socksHost: 'localhost',
            socksPost: 9050,
        },
```

**Comment by rightaway** [comment]
Or if I try `agentClass: new SocksProxyAgent('socks://127.0.0.1:9050'),` I get an error `TypeError: object is not a function`

**Comment by TooTallNate** [comment]
Can you give me the full stack trace?

**Comment by TooTallNate** [comment]
Honestly though, it looks like request has its own proxy support baked-in (kinda anti-modular... but ya...). You'll probably need to ask on `request`'s issue tracker, since it should just be a matter of passing `agent: new SocksProxyAgent('socks://127.0.0.1:9050')` if this were the core `http` module.
